### ISSUE TITLE
Chronicle logger tools not reading logs

### ISSUE THREAD

**Issue by AdalyatNazirov** [OpenHFT/Chronicle-Logger#121]
I've switched from Simple Logger to chronicle-logger-slf4j is an implementation of SLF4J API and seems it works so logs files are created and it's not empty. But now I'm trying to read the file using `ChroniCat` shipped in `chronicle-logger-tools`.

I tried the standard approach described in the docs that is 
```
mvn exec:java -Dexec.mainClass="net.openhft.chronicle.logger.tools.ChroniCat" -Dexec.args="…​"
```
but it required a `pom.xml` file. Even I create one it still with `Unauthorized (401)` reason
> Failed to execute goal on project chronicle-execution-engine.logger: Could not resolve dependencies for project chronicle-execution-engine:chronicle-execution-engine.logger:jar:1: Failed to collect dependencies at net.openhft:chronicle-logger-core:jar:4.20.1 -> net.openhft:chronicle-wire:jar:2.20.4 -> net.openhft:chronicle-core:jar:2.20.6-SNAPSHOT: Failed to read artifact descriptor for net.openhft:chronicle-core:jar:2.20.6-SNAPSHOT: Could not transfer artifact net.openhft:chronicle-core:pom:2.20.6-SNAPSHOT from/to chronicle-enterprise-snapshots (https://nexus.chronicle.software/content/repositories/snapshots): status code: 401, reason phrase: Unauthorized (401)

Another way I tried is running `ChroniCat` in the `Java` directly. My code is 
```
public static void main(String[] args) throws FileNotFoundException {
        ChroniCat.main(new String[]{"./slf4j.chronicle.base/main"});
}
```
In this case I've got an error 
> java.lang.IllegalArgumentException: primitive: void
	at net.openhft.chronicle.core.util.ObjectUtils.supplierForClass(ObjectUtils.java:96)
	at net.openhft.chronicle.core.ClassLocal.computeValue(ClassLocal.java:54)
	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
	at net.openhft.chronicle.core.util.ObjectUtils.newInstance(ObjectUtils.java:409)
	at net.openhft.chronicle.wire.WireInternal.throwable(WireInternal.java:246)
	at net.openhft.chronicle.wire.ValueIn.throwable(ValueIn.java:494)
	at net.openhft.chronicle.logger.tools.ChronicleLogReader.processLogs(ChronicleLogReader.java:122)
	at net.openhft.chronicle.logger.tools.ChroniCat.main(ChroniCat.java:42)
	at com.myorg.DumpLog.main(DumpLog.java:9)
	
Can someone share the way to dump logs to STDOUT?

**Comment by JerryShea** [comment]
Hi @AdalyatNazirov yep, the tools submodule was commented out a while ago. We have now added it back so try the latest version from the main `ea` branch. A new version will be released soon.

In future it is best to ask questions on stackoverflow.

(edited)
