### ISSUE TITLE
Chronicle-Logger doesn't work on  Solaris/SPARC due to unsafe memory access

### ISSUE THREAD

**Issue by n4al** [OpenHFT/Chronicle-Logger#128]
I am trying to build the latest snapshot of Chronicle-Logger on Solaris 11/SPARC architecture and JDK 14, but the tests are hitting the following problem:
`
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.034 s <<< FAILURE! - in net.openhft.chronicle.logger.DefaultChronicleLogWriterTest
[ERROR] net.openhft.chronicle.logger.DefaultChronicleLogWriterTest.testWrite  Time elapsed: 0.825 s  <<< ERROR!
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at net.openhft.chronicle.wire.BinaryWire$FixedBinaryValueOut.marshallable(BinaryWire.java:2006)
        at net.openhft.chronicle.wire.ValueOut.typedMarshallable(ValueOut.java:623)
        at net.openhft.chronicle.wire.ValueOut.object(ValueOut.java:937)
        at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.writeTableStore(SingleTableBuilder.java:175)
        at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.lambda$build$2(SingleTableBuilder.java:140)
        at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithLock(SingleTableStore.java:141)
        at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithExclusiveLock(SingleTableStore.java:124)
        at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.build(SingleTableBuilder.java:137)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.initializeMetadata(SingleChronicleQueueBuilder.java:452)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.preBuild(SingleChronicleQueueBuilder.java:1091)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:325)
        at net.openhft.chronicle.logger.DefaultChronicleLogWriterTest.testWrite(DefaultChronicleLogWriterTest.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
`

that's typically an issue of memory alignment that is strictly enforced by SPARC CPUs.

Please let me know if you need more information or if I can help with access to a SPARC machine.

**Comment by JerryShea** [comment]
We [don't support SPARC](https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Platform-Support.adoc) and we [don't support Java 14](https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Java-Version-Support.adoc).

Thanks for the offer of a SPARC machine, but SPARC but it is a very uncommon platform for our clients nowadays and we won't be able to support it unless someone is prepared to sponsor the development effort. If you would like to discuss that, please contact info@chronicle.software.
