### ISSUE TITLE
NoClassDefFoundError: net/openhft/chronicle/VanillaChronicleConfig

### ISSUE THREAD

**Issue by serge98** [OpenHFT/Chronicle-Logger#16]
In which jar is VanillaChronicleConfig? (Looking at https://repo1.maven.org/maven2/net/openhft/)
The sources appear to be in https://github.com/OpenHFT/Chronicle-Queue/tree/master/chronicle-sandbox/src/main/java/net/openhft/chronicle/sandbox, but is it included in any package?

**Comment by lburgazzoli** [comment]
Chronicle-Logger 1.0.x is not yet compatible with chronicle 3.3.x, you should use [chronicle 3.2.5](http://search.maven.org/#artifactdetails|net.openhft|chronicle|3.2.5|bundle)

**Comment by serge98** [comment]
Thanks, I passed through this obstacle now, and some other required dependencies as well. It'd be great is required packages and their versions were listed somewhere.
I'm now on this error in trying to use the logger. May it be caused by a wrong version as well?
NullPointerException
    at net.openhft.affinity.AffinitySupport.getThreadId(AffinitySupport.java:155)

**Comment by lburgazzoli** [comment]
If you use maven/gradle to set-up you project, dependencies are automatically resolved.
On which OS ?

**Comment by serge98** [comment]
It's Linux. I'm trying to add necessary jars into classpath, for a test application which is logging via slf4j, no maven/gradle is involved.

**Comment by lburgazzoli** [comment]
Usually AffinitySupport.getThreadId's NPE happens because you do not have JNA in your classpath.

- [net.java.dev.jna:jna:4.1.0](http://search.maven.org/#artifactdetails|net.java.dev.jna|jna|4.1.0|jar)
- [net.java.dev.jna:jna-platform:4.1.0](http://search.maven.org/#artifactdetails|net.java.dev.jna|jna-platform|4.1.0|jar)

**Comment by serge98** [comment]
Is it possible to extract the required dependencies from pom files accompanying the jars?
I'm on this error now:
NoSuchMethodError: net.openhft.lang.Maths.hash(J)I
    at net.openhft.chronicle.DateCache.formatFor(DateCache.java:52)

**Comment by serge98** [comment]
Answering my previous concern, the required version of net.openhft.lang is lang-6.4.10. The signature of one of the hash methods changes after that.
Again, how can one figure out what versions are required upfront, without dealing with all these errors?

**Comment by lburgazzoli** [comment]
this is the output of mvn dependency:tree. It lists all the dependencies of master tree including test dependencies:

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] OpenHFT/Chronicle-Logger
[INFO] OpenHFT/Chronicle-Logger/logger
[INFO] OpenHFT/Chronicle-Logger/logger-slf4j
[INFO] OpenHFT/Chronicle-Logger/logger-logback
[INFO] OpenHFT/Chronicle-Logger/logger-log4j-1
[INFO] OpenHFT/Chronicle-Logger/logger-log4j-2
[INFO] OpenHFT/Chronicle-Logger/logger-tools
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building OpenHFT/Chronicle-Logger 1.0.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ chronicle-logger-parent ---
[INFO] net.openhft:chronicle-logger-parent:pom:1.0.4-SNAPSHOT
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building OpenHFT/Chronicle-Logger/logger 1.0.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ chronicle-logger ---
[INFO] net.openhft:chronicle-logger:jar:1.0.4-SNAPSHOT
[INFO] +- net.openhft:chronicle:jar:3.2.5:compile
[INFO] |  +- net.openhft:lang:jar:6.4.10:compile
[INFO] |  |  +- com.sun.java:tools:jar:1.8.0_25:system
[INFO] |  |  \- net.openhft:compiler:jar:2.2.0:compile
[INFO] |  +- net.openhft:affinity:jar:2.1.2:compile
[INFO] |  |  +- net.java.dev.jna:jna:jar:4.1.0:compile
[INFO] |  |  +- net.java.dev.jna:jna-platform:jar:4.1.0:compile
[INFO] |  |  \- org.kohsuke.jetbrains:annotations:jar:9.0:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.6:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.3.1:test
[INFO] +- junit:junit:jar:4.11:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] \- org.slf4j:slf4j-simple:jar:1.7.6:test
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building OpenHFT/Chronicle-Logger/logger-slf4j 1.0.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ chronicle-logger-slf4j ---
[INFO] net.openhft:chronicle-logger-slf4j:bundle:1.0.4-SNAPSHOT
[INFO] +- net.openhft:chronicle-logger:jar:1.0.4-SNAPSHOT:compile
[INFO] +- net.openhft:chronicle:jar:3.2.5:compile
[INFO] |  +- net.openhft:lang:jar:6.4.10:compile
[INFO] |  |  +- com.sun.java:tools:jar:1.8.0_25:system
[INFO] |  |  \- net.openhft:compiler:jar:2.2.0:compile
[INFO] |  \- net.openhft:affinity:jar:2.1.2:compile
[INFO] |     +- net.java.dev.jna:jna:jar:4.1.0:compile
[INFO] |     +- net.java.dev.jna:jna-platform:jar:4.1.0:compile
[INFO] |     \- org.kohsuke.jetbrains:annotations:jar:9.0:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.6:compile
[INFO] +- org.slf4j:jul-to-slf4j:jar:1.7.6:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.3.1:test
[INFO] +- junit:junit:jar:4.11:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.openjdk.jmh:jmh-core:jar:1.3.3:test
[INFO] |  +- net.sf.jopt-simple:jopt-simple:jar:4.6:test
[INFO] |  \- org.apache.commons:commons-math3:jar:3.2:test
[INFO] \- org.openjdk.jmh:jmh-core-benchmarks:jar:1.3.3:test
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building OpenHFT/Chronicle-Logger/logger-logback 1.0.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ chronicle-logger-logback ---
[INFO] net.openhft:chronicle-logger-logback:bundle:1.0.4-SNAPSHOT
[INFO] +- net.openhft:chronicle-logger:jar:1.0.4-SNAPSHOT:compile
[INFO] +- net.openhft:chronicle:jar:3.2.5:compile
[INFO] |  +- net.openhft:lang:jar:6.4.10:compile
[INFO] |  |  +- com.sun.java:tools:jar:1.8.0_25:system
[INFO] |  |  \- net.openhft:compiler:jar:2.2.0:compile
[INFO] |  \- net.openhft:affinity:jar:2.1.2:compile
[INFO] |     +- net.java.dev.jna:jna:jar:4.1.0:compile
[INFO] |     +- net.java.dev.jna:jna-platform:jar:4.1.0:compile
[INFO] |     \- org.kohsuke.jetbrains:annotations:jar:9.0:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.6:compile
[INFO] +- org.slf4j:jul-to-slf4j:jar:1.7.6:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.1.2:compile
[INFO] |  \- ch.qos.logback:logback-core:jar:1.1.2:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.3.1:test
[INFO] \- junit:junit:jar:4.11:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building OpenHFT/Chronicle-Logger/logger-log4j-1 1.0.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ chronicle-logger-log4j-1 ---
[INFO] net.openhft:chronicle-logger-log4j-1:bundle:1.0.4-SNAPSHOT
[INFO] +- net.openhft:chronicle-logger:jar:1.0.4-SNAPSHOT:compile
[INFO] +- net.openhft:chronicle:jar:3.2.5:compile
[INFO] |  +- net.openhft:lang:jar:6.4.10:compile
[INFO] |  |  +- com.sun.java:tools:jar:1.8.0_25:system
[INFO] |  |  \- net.openhft:compiler:jar:2.2.0:compile
[INFO] |  \- net.openhft:affinity:jar:2.1.2:compile
[INFO] |     +- net.java.dev.jna:jna:jar:4.1.0:compile
[INFO] |     +- net.java.dev.jna:jna-platform:jar:4.1.0:compile
[INFO] |     \- org.kohsuke.jetbrains:annotations:jar:9.0:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.6:compile
[INFO] +- org.slf4j:jul-to-slf4j:jar:1.7.6:compile
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.7.6:compile
[INFO] +- log4j:log4j:jar:1.2.17:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.3.1:test
[INFO] \- junit:junit:jar:4.11:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building OpenHFT/Chronicle-Logger/logger-log4j-2 1.0.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ chronicle-logger-log4j-2 ---
[INFO] net.openhft:chronicle-logger-log4j-2:bundle:1.0.4-SNAPSHOT
[INFO] +- net.openhft:chronicle-logger:jar:1.0.4-SNAPSHOT:compile
[INFO] +- net.openhft:chronicle:jar:3.2.5:compile
[INFO] |  +- net.openhft:lang:jar:6.4.10:compile
[INFO] |  |  +- com.sun.java:tools:jar:1.8.0_25:system
[INFO] |  |  \- net.openhft:compiler:jar:2.2.0:compile
[INFO] |  \- net.openhft:affinity:jar:2.1.2:compile
[INFO] |     +- net.java.dev.jna:jna:jar:4.1.0:compile
[INFO] |     +- net.java.dev.jna:jna-platform:jar:4.1.0:compile
[INFO] |     \- org.kohsuke.jetbrains:annotations:jar:9.0:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.6:compile
[INFO] +- org.slf4j:jul-to-slf4j:jar:1.7.6:compile
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.0.2:compile
[INFO] +- org.apache.logging.log4j:log4j-api:jar:2.1:compile
[INFO] +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.1:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.3.1:test
[INFO] \- junit:junit:jar:4.11:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building OpenHFT/Chronicle-Logger/logger-tools 1.0.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ chronicle-logger-tools ---
[INFO] net.openhft:chronicle-logger-tools:jar:1.0.4-SNAPSHOT
[INFO] +- net.openhft:chronicle-logger:jar:1.0.4-SNAPSHOT:compile
[INFO] +- net.openhft:chronicle:jar:3.2.5:compile
[INFO] |  +- net.openhft:lang:jar:6.4.10:compile
[INFO] |  |  +- com.sun.java:tools:jar:1.8.0_25:system
[INFO] |  |  \- net.openhft:compiler:jar:2.2.0:compile
[INFO] |  \- net.openhft:affinity:jar:2.1.2:compile
[INFO] |     +- net.java.dev.jna:jna:jar:4.1.0:compile
[INFO] |     +- net.java.dev.jna:jna-platform:jar:4.1.0:compile
[INFO] |     \- org.kohsuke.jetbrains:annotations:jar:9.0:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.6:compile
[INFO] +- org.slf4j:slf4j-simple:jar:1.7.6:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.3.1:test
[INFO] \- junit:junit:jar:4.11:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
```

**Comment by serge98** [comment]
Thanks Luca for helping with resolving it!

It's still inconvenient that source poms are required to figure out the dependencies. It'd be useful if dependency tree was made available with the jars.

**Comment by lburgazzoli** [comment]
I think that using maven/gradle is the best way to solve dependecies so that you can automatically get the dependencies we have testes agains and you do not have to manually deal with them.
 
@peter-lawrey @BoundedBuffer whould we list dependencies on project web-page ?
