### ISSUE TITLE
ChronicleLogReader fails while running processLog()

### ISSUE THREAD

**Issue by danke02** [OpenHFT/Chronicle-Logger#59]
Hello again.
I wrote simple log with logback+chronicleAppender and read it with ChroniCat. I tried simple way found on chronicle-logger github page. Exception occured while running ChronicleLogReadr::processLog() trying to process "throwable" field which not exists in my case. I temporarily solved this problem by writing my custom ChronicleLogReader omitting "throwable" part. 

Below is an exception message
```
java.lang.IllegalArgumentException: primitive: void
	at net.openhft.chronicle.core.util.ObjectUtils.lambda$static$3(ObjectUtils.java:75)
	at net.openhft.chronicle.core.ClassLocal.computeValue(ClassLocal.java:53)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209)
	at java.lang.ClassValue.get(ClassValue.java:115)
	at net.openhft.chronicle.core.util.ObjectUtils.newInstance(ObjectUtils.java:348)
	at net.openhft.chronicle.wire.WireInternal.throwable(WireInternal.java:208)
	at net.openhft.chronicle.wire.ValueIn.throwable(ValueIn.java:552)
	at net.openhft.chronicle.logger.tools.ChronicleLogReader.processLogs(ChronicleLogReader.java:122)
	at net.openhft.chronicle.logger.tools.ChroniCat.main(ChroniCat.java:41)
```

Below is my logback setting
```
<appender name="CHRONICLE_FILE" class="net.openhft.chronicle.logger.logback.ChronicleAppender">
		<path>${USER_HOME}/ap/chronicle</path>
		<chronicleConfig>
		  <blockSize>128</blockSize>
		</chronicleConfig>
	</appender>
```

Below is the code that I used to write log.
```
for (int i = 0; i < iter; ++i) {
            DefaultLogger.logger.info("default value long={} double={} str={}", longs[i], doubles[i], strs[i]);
        }
```

**Comment by dpisklov** [comment]
I'm not sure what exactly you are doing wrong but it works for me, see below the test I run and config:

```
public class ChronicleLogReaderTest {
    @Before
    public void setup() {
        System.setProperty(
                "logback.configurationFile",
                System.getProperty("resources.path")
                        + "/logback-chronicle-binary-appender.xml");
    }

    @Test
    public void readTest() {
        final Logger logger = LoggerFactory.getLogger("binary-chronicle");
        logger.info("test {} {} {}", 1, 100L, 100.123D);
        logger.info("test {} {} {}", 2, 100L, 100.123D);
        logger.info("test {} {} {}", 3, 100L, 100.123D);


        ChronicleLogReader reader = new ChronicleLogReader(System.getProperty("java.io.tmpdir") + "/chronicle-logback/binary-chronicle", WireType.BINARY_LIGHT);
        reader.processLogs(ChronicleLogReader::printf, false);

        //ChroniCat.main(new String[] {System.getProperty("java.io.tmpdir") + "/chronicle-logback/binary-chronicle"});
    }
}
```

Logback config:
```
<configuration>

    <appender name  = "STDOUT"
              class = "ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <Pattern>%d %contextName [%t] %level %logger{36} - %msg%n</Pattern>
        </encoder>
    </appender>
    <appender name  = "BINARY-CHRONICLE"
              class = "net.openhft.chronicle.logger.logback.ChronicleAppender">
        <path>${java.io.tmpdir}/chronicle-logback/binary-chronicle</path>
        <includeCallerData>false</includeCallerData>
        <includeMappedDiagnosticContext>false</includeMappedDiagnosticContext>
        <chronicleConfig>
            <blockSize>128</blockSize>
        </chronicleConfig>
    </appender>

    <logger name="binary-chronicle" level="TRACE" additivity="false">
        <appender-ref ref="BINARY-CHRONICLE"/>
    </logger>

    <logger name="net.openhft" level="WARN" additivity="false">
        <appender-ref ref="STDOUT" />
    </logger>

    <root level="DEBUG">
        <appender-ref ref="STDOUT" />
    </root>

</configuration>
```

**Comment by dpisklov** [comment]
Closing as it seems to work - feel free to reopen and provide more information.
